In [1]:
# Import required libraries
import tensorflow as tf
import numpy as np
import string

# Define input sequences
inputs = np.array([
    ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S"],
    ["Z", "Y", "X", "W", "V", "U", "T", "S", "R", "Q", "P", "O", "N", "M", "L", "K", "J", "I", "H"],
    ["B", "D", "F", "H", "J", "L", "N", "P", "R", "T", "V", "X", "Z", "A", "C", "E", "G", "I", "K"],
    ["M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E"],
    ["H", "G", "F", "E", "D", "C", "B", "A", "L", "K", "J", "I", "P", "O", "N", "M", "U", "T", "S"],
])

# Define expected output sequences
expected = np.array([
    ["B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"],
    ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S"],
    ["C", "E", "G", "I", "K", "M", "O", "Q", "S", "U", "W", "Y", "A", "B", "D", "F", "H", "J", "L"],
    ["N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A", "B", "C", "D", "E", "F"],
    ["I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "A"],
])

In [3]:
# Encode characters to numeric indices
input_encoded = np.vectorize(string.ascii_uppercase.index)(inputs)
input_encoded = input_encoded.astype(np.float32)
print(input_encoded)

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18.]
 [25. 24. 23. 22. 21. 20. 19. 18. 17. 16. 15. 14. 13. 12. 11. 10.  9.  8.
   7.]
 [ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25.  0.  2.  4.  6.  8.
  10.]
 [12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25.  0.  1.  2.  3.
   4.]
 [ 7.  6.  5.  4.  3.  2.  1.  0. 11. 10.  9.  8. 15. 14. 13. 12. 20. 19.
  18.]]


In [4]:
one_hot_inputs = tf.keras.utils.to_categorical(input_encoded)
print(one_hot_inputs)

[[[1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 1. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 1.]
  [0. 0. 0. ... 0. 1. 0.]
  [0. 0. 0. ... 1. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 1. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [ ]:
expected_encoded = np.vectorize(string.ascii_uppercase.index)(expected)
expected_encoded = expected_encoded.astype(np.float32)
one_hot_expected = tf.keras.utils.to_categorical(expected_encoded)

# Build the RNN model
model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(128, return_sequences=True),
    tf.keras.layers.Dense(len(string.ascii_uppercase)),
])

# Compile the model
model.compile(loss="categorical_crossentropy", optimizer="adam")

# Train the model
model.fit(one_hot_inputs, one_hot_expected, epochs=100)


Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 8.4553
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 7.8425
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 7.8253
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 8.0672
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 8.0553
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - loss: 8.3442
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 8.1966
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 8.3628
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 8.2882
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 8.4052
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 8.6972
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 8.6492
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 8.6018
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 8.7877
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 9.0698
Epoch 16/100
1/1 ━━━━

In [ ]:
# Inspect model weights
for i, layer in enumerate(model.layers):
    print(f"\nLayer {i + 1}: {layer.name}")
    weights = layer.get_weights()
    if weights:
        if "rnn" in layer.name.lower():
            print("RNN Layer Weights:")
            print(f"Input weights shape: {weights[0].shape}")
            print(f"Recurrent weights shape: {weights[1].shape}")
            print(f"Bias shape: {weights[2].shape}")
        elif "dense" in layer.name.lower():
            print("Dense Layer Weights:")
            print(f"Weights shape: {weights[0].shape}")
            print(f"Bias shape: {weights[1].shape}")

# Summarize the model
model.summary()


Layer 1: simple_rnn_2
RNN Layer Weights:
Input weights shape: (26, 128)
Recurrent weights shape: (128, 128)
Bias shape: (128,)

Layer 2: dense_2
Dense Layer Weights:
Weights shape: (128, 26)
Bias shape: (26,)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn_2 (SimpleRNN)             │ (None, 19, 128)             │          19,840 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 19, 26)              │           3,354 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 69,584 (271.82 KB)

 Trainable params: 23,194 (90.60 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 46,390 (181.21 KB)

In [ ]:
# Make a prediction on new data
new_inputs = np.array([["B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"]])
new_inputs_encoded = np.vectorize(string.ascii_uppercase.index)(new_inputs)
new_inputs_encoded = new_inputs_encoded.astype(np.float32)
# Specify num_classes to ensure consistent one-hot encoding
new_inputs_encoded = tf.keras.utils.to_categorical(new_inputs_encoded, num_classes=len(string.ascii_uppercase))

# Predict the next character
prediction = model.predict(new_inputs_encoded)
predicted_index = np.argmax(prediction[0][-1])
print(f"Predicted next character: {string.ascii_uppercase[predicted_index]}")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step
Predicted next character: Y


In [ ]:
# Import required libraries
import tensorflow as tf
import numpy as np
import string

# Generate a larger dataset
alphabet = string.ascii_uppercase
dataset_size = 1000  # Increase dataset size
sequence_length = 20

inputs = []
expected = []

for _ in range(dataset_size):
    start = np.random.randint(0, len(alphabet) - sequence_length - 1)
    sequence = alphabet[start : start + sequence_length]
    next_char = alphabet[start + 1 : start + sequence_length + 1]
    inputs.append(list(sequence))
    expected.append(list(next_char))

inputs = np.array(inputs)
expected = np.array(expected)

In [ ]:
inputs[:2]

array([['B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
        'O', 'P', 'Q', 'R', 'S', 'T', 'U'],
       ['D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
        'Q', 'R', 'S', 'T', 'U', 'V', 'W']], dtype='<U1')

In [ ]:
# Encode characters to numeric indices and one-hot encode
def encode_sequences(data, alphabet):
    indices = np.vectorize(alphabet.index)(data)
    one_hot_encoded = tf.keras.utils.to_categorical(indices, num_classes=len(alphabet))
    return one_hot_encoded

one_hot_inputs = encode_sequences(inputs, alphabet)
one_hot_expected = encode_sequences(expected, alphabet)

# Build an improved RNN model
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(128, return_sequences=True, input_shape=(sequence_length, len(alphabet))),
    tf.keras.layers.Dropout(0.2),  # Prevent overfitting
    tf.keras.layers.Dense(len(alphabet), activation="softmax"),
])

# Compile the model
model.compile(
    loss="categorical_crossentropy",
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    metrics=["accuracy"],
)

# Train the model
history = model.fit(
    one_hot_inputs,
    one_hot_expected,
    epochs=50,
    batch_size=32,
    validation_split=0.2,
    callbacks=[tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)],
)

# Inspect model summary
model.summary()

# Predict on new data
test_input = np.array([list("ABCDEFGHIJKLMNOPQRST")])  # Example input
test_one_hot = encode_sequences(test_input, alphabet)

prediction = model.predict(test_one_hot)
predicted_indices = np.argmax(prediction[0], axis=1)
predicted_chars = "".join([alphabet[idx] for idx in predicted_indices])

print(f"Input: {''.join(test_input[0])}")
print(f"Predicted Next Characters: {predicted_chars}")

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 51s 17ms/step - accuracy: 0.1217 - loss: 3.1600 - val_accuracy: 0.2373 - val_loss: 2.5443
Epoch 2/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2924 - loss: 2.2833 - val_accuracy: 0.6112 - val_loss: 1.6150
Epoch 3/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5536 - loss: 1.5205 - val_accuracy: 0.7757 - val_loss: 1.1803
Epoch 4/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7331 - loss: 1.1397 - val_accuracy: 0.8373 - val_loss: 0.9207
Epoch 5/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8203 - loss: 0.8878 - val_accuracy: 0.8827 - val_loss: 0.7347
Epoch 6/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8696 - loss: 0.7150 - val_accuracy: 0.9015 - val_loss: 0.5871
Epoch 7/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9048 - loss: 0.5733 - val_accuracy: 0.9423 - val_loss: 0.4645
Epoch 8/50
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9399 - loss: 0.4509 - val_accuracy: 0.9555 - val_los

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 20, 128)             │          79,360 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 20, 128)             │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 20, 26)              │           3,354 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 248,144 (969.32 KB)

 Trainable params: 82,714 (323.10 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 165,430 (646.21 KB)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step
Input: ABCDEFGHIJKLMNOPQRST
Predicted Next Characters: BCDEFGHIJKLMNOPQRSTU
